{
  config,
  lib,
  pkgs,
  hostName,
  ...
}:
with lib; {
  # Setup the user account.
  home.username = "bean";
  home.homeDirectory = "/home/bean";

  home.stateVersion = "23.05";

  # Enable management of known folders
  xdg = {
    enable = true;
    userDirs = {enable = true;};
  };

  qt = {
    enable = true;
    platformTheme = "qtct";
  };

  xdg.configFile."Kvantum/kvantum.kvconfig".text = ''
    [General]
    theme=Sweet-Ambar-Blue
  '';

  xdg.configFile."gtklock/config.ini".text = ''
    [main]
    gtk-theme=Sweet-Ambar-Blue
    background=${./res/pictures/background.jpg}
    idle-hide=true
    style=${./res/gtklock-style.css}
    start-hidden=true
    modules=/run/current-system/sw/lib/gtklock/userinfo-module.so
  '';

  # Hyprland
  wayland.windowManager.hyprland = {
    enable = true;
    settings = {
      env = [
        "GTK_THEME,Sweet-Ambar-Blue:dark"
        "QT_QPA_PLATFORMTHEME,qt5ct"
      ];
      autogenerated = 0;
      monitor = ",2256x1504@60,0x0,1";
      decoration = {
        rounding = 10;
      };
      exec-once = [
        "keepassxc /home/bean/Documents/Database.kdbx"
        "waybar"
        "swaync"
        "swayosd-server"
        "nm-applet"
      ];
      input = {
        numlock_by_default = true;
        touchpad = {
          natural_scroll = true;
        };
      };
      gestures = {
        workspace_swipe = true;
      };
      bind = [
        "SUPER,S,exec,rofi -show drun"
        "SUPER,Q,exec,firefox"
        "SUPER,E,exec,dolphin"
        "SUPER,T,exec,kitty"
        "SUPER,N,exec,swaync-client -t -sw"
        "SUPER,L,exec,gtklock"
        "SUPER,C,killactive,"
        "SUPER,M,exit,"
        "SUPER,V,togglefloating,"
        "SUPER,P,pseudo,"
        "SUPER,J,togglesplit,"
        "SUPER,left,movefocus,l"
        "SUPER,right,movefocus,r"
        "SUPER,up,movefocus,u"
        "SUPER,down,movefocus,d"
        "SUPER,1,workspace,1"
        "SUPER,2,workspace,2"
        "SUPER,3,workspace,3"
        "SUPER,4,workspace,4"
        "SUPER,5,workspace,5"
        "SUPER,6,workspace,6"
        "SUPER,7,workspace,7"
        "SUPER,8,workspace,8"
        "SUPER,9,workspace,9"
        "SUPER,0,workspace,10"
        "SUPER SHIFT,1,movetoworkspace,1"
        "SUPER SHIFT,2,movetoworkspace,2"
        "SUPER SHIFT,3,movetoworkspace,3"
        "SUPER SHIFT,4,movetoworkspace,4"
        "SUPER SHIFT,5,movetoworkspace,5"
        "SUPER SHIFT,6,movetoworkspace,6"
        "SUPER SHIFT,7,movetoworkspace,7"
        "SUPER SHIFT,8,movetoworkspace,8"
        "SUPER SHIFT,9,movetoworkspace,9"
        "SUPER SHIFT,0,movetoworkspace,10"
        "SUPER SHIFT,S,exec,watershot -c directory /home/bean/Pictures"
        "SUPER SHIFT,R,exec,wl-screenrec -g \"$(slurp)\""
        "SUPER SHIFT ALT,R,exec,wl-screenrec"
        ",XF86AudioRaiseVolume,exec,swayosd-client --output-volume raise"
        ",XF86AudioLowerVolume,exec,swayosd-client --output-volume lower"
        ",XF86AudioMute,exec,swayosd-client --output-volume mute-toggle"
        ",XF86MonBrightnessUp,exec,swayosd-client --brightness raise"
        ",XF86MonBrightnessDown,exec,swayosd-client --brightness lower"
      ];
      bindm = [
        "SUPER,mouse:272,movewindow"
        "SUPER,mouse:273,resizewindow"
      ];
      xwayland = {
        force_zero_scaling = true;
      };
      misc = {
        disable_hyprland_logo = true;
      };
    };
  };

  xdg.configFile.waybar.source = ./res/waybar;

  programs = {
    # Shell
    starship = {
      enable = true;
      settings = fromTOML (fileContents ./res/starship.toml);
    };

    nushell = {
      enable = true;
      configFile.text = ''
        $env.config = { show_banner: false }
      '';
      envFile.text = ''
        alias py = python
        alias cat = bat
      '';
    };

    # CLI Tools
    bat.enable = true;
    ripgrep.enable = true;
    gh = {
      enable = true;
      gitCredentialHelper.enable = true;
    };
    neovim = {
      enable = true;
      viAlias = true;
      vimAlias = true;
    };

    # Plasma
    plasma = {
      enable = true;

      configFile = {
        kdeglobals = {
          KDE = {
            LookAndFeelPackage = "Sweet-Ambar-Blue";
            Single-Click = false;
          };
        };
        kwinrc = {
          Plugins = {
            kwin4_effect_dimscreenEnabled = true;
            kwin4_effect_squashEnabled = false;
            magiclampEnabled = true;
            mouseclickEnabled = true;
            sheetEnabled = true;
            wobblywindowsEnabled = true;
          };
          Effect-wobblywindows = {
            Drag = 85;
            Stiffness = 10;
            WobblynessLevel = 1;
          };
          NightColor = {
            Active = true;
            NightTemperature = 3500;
          };
        };
        plasmarc = {Wallpapers.usersWallpapers = "${./res/pictures/background.jpg}";};
        kcminputrc = {Keyboard.NumLock = 1;};
        konsolerc = {"Desktop Entry".DefaultProfile = "Main.profile";};
        spectaclerc = {General.clipboardGroup = "PostScreenshotCopyImage";};
      };
    };

    # GUI Apps
    chromium.enable = true;
    thunderbird = {
      enable = true;
      profiles.bean.isDefault = true;
    };
  };

  # Enable KDE Connect
  services.kdeconnect.enable = true;

  # Set the user profile picture to my cow
  home.file.".face.icon".source = ./res/pictures/cow.png;

  # Set my applet layouts and pictures
  xdg.configFile."plasma-org.kde.plasma.desktop-appletsrc".text = replaceStrings ["~~BACKGROUND~~"] ["${./res/pictures/background.jpg}"] (fileContents ./res/plasma-org.kde.plasma.desktop-appletsrc);
  xdg.configFile."kscreenlockerrc".text = replaceStrings ["~~BACKGROUND~~"] ["${./res/pictures/background.jpg}"] (fileContents ./res/kscreenlockerrc);

  # Set Konsole profile
  xdg.dataFile."konsole/Main.profile".text = ''
    [Appearance]
    AntiAliasFonts=true
    BoldIntense=true
    ColorScheme=Sweet-Ambar-Blue
    Font=FiraMono Nerd Font Mono,12,-1,5,50,0,0,0,0,0
    LineSpacing=0
    UseFontLineChararacters=false

    [General]
    Command=nu
    DimWhenInactive=false
    Environment=TERM=konsole-256color,COLORTERM=truecolor
    InvertSelectionColors=false
    Name=Main
    Parent=FALLBACK/
  '';

  home.file.".gtkrc-2.0".text = ''
    gtk-application-prefer-dark-theme=1
    gtk-theme-name="Sweet-Ambar-Blue"
    gtk-enable-animations=1
    gtk-primary-button-warps-slider=0
    gtk-toolbar-style=3
    gtk-menu-images=1
    gtk-button-images=1
    gtk-cursor-theme-size=24
    gtk-cursor-theme-name="Sweet-cursors"
    gtk-icon-theme-name="candy-icons"
    gtk-font-name="FiraMono Nerd Font Mono,  10"

    gtk-modules=appmenu-gtk-module
  '';

  xdg.configFile."gtk-3.0/settings.ini".text = ''
    [Settings]
    gtk-application-prefer-dark-theme=1
    color-scheme=prefer-dark
    gtk-button-images=true
    gtk-cursor-theme-name=Sweet-cursors
    gtk-cursor-theme-size=24
    gtk-decoration-layout=icon:minimize,maximize,close
    gtk-enable-animations=true
    gtk-font-name=FiraMono Nerd Font Mono,  10
    gtk-icon-theme-name=candy-icons
    gtk-menu-images=true
    gtk-modules=colorreload-gtk-module:window-decorations-gtk-module:appmenu-gtk-module
    gtk-primary-button-warps-slider=false
    gtk-shell-shows-menubar=1
    gtk-theme-name=Sweet-Ambar-Blue
    gtk-toolbar-style=3
    gtk-xft-dpi=98304
  '';

  xdg.configFile."gtk-4.0/settings.ini".text = ''
    [Settings]
    gtk-application-prefer-dark-theme=1
    color-scheme=prefer-dark
    gtk-cursor-theme-name=Sweet-cursors
    gtk-cursor-theme-size=24
    gtk-decoration-layout=icon:minimize,maximize,close
    gtk-enable-animations=true
    gtk-font-name=FiraMono Nerd Font Mono,  10
    gtk-icon-theme-name=candy-icons
    gtk-primary-button-warps-slider=false
    gtk-xft-dpi=98304
  '';

  xdg.configFile."kdeconnect/config".text = ''
    [General]
    name=${hostName}
  '';

  # Set the default applications
  xdg.mimeApps = {
    enable = true;
    defaultApplications = {
      "text/html" = ["firefox.desktop" "chromium.desktop"];
      "x-scheme-handler/http" = ["firefox.desktop" "chromium.desktop"];
      "x-scheme-handler/https" = ["firefox.desktop" "chromium.desktop"];
      "x-scheme-handler/chrome" = ["firefox.desktop" "chromium.desktop"];
      "x-scheme-handler/vscode" = ["code-url-handler.desktop"];
      "application/x-extension-htm" = ["firefox.desktop" "chromium.desktop"];
      "application/x-extension-html" = ["firefox.desktop" "chromium.desktop"];
      "application/x-extension-shtml" = ["firefox.desktop" "chromium.desktop"];
      "application/x-extension-xht" = ["firefox.desktop" "chromium.desktop"];
      "application/x-extension-xhtml" = ["firefox.desktop" "chromium.desktop"];
      "application/xhtml+xml" = ["firefox.desktop" "chromium.desktop"];
      "application/pdf" = ["firefox.desktop" "chromium.desktop"];
      "inode/directory" = ["org.kde.dolphin.desktop"];
      "x-scheme-handler/mailto" = ["userapp-Thunderbird-WKLTC2.desktop"];
      "message/rfc822" = ["userapp-Thunderbird-WKLTC2.desktop"];
      "x-scheme-handler/mid" = ["userapp-Thunderbird-WKLTC2.desktop"];
      "text/plain" = ["org.kde.kate.desktop"];
      "x-scheme-handler/x-github-client" = ["github-desktop.desktop"];
      "x-scheme-handler/x-github-desktop-auth" = ["github-desktop.desktop"];
    };
  };
}
