{
  config,
  lib,
  pkgs,
  hostName,
  ...
}:
with lib; rec {
  home = {
    username = "bean";
    homeDirectory = "/home/bean";
    stateVersion = "23.05";
    file = {
      ".face".source = ./res/pictures/cow.png;
      ".gtkrc-2.0".source = ./res/gtk/.gtkrc-2.0;
    };
    activation = {
      createXDGFoldersAction = lib.hm.dag.entryAfter ["writeBoundary"] ''
        mkdir -p $HOME/Desktop
        mkdir -p $HOME/Documents
        mkdir -p $HOME/Pictures
        mkdir -p $HOME/Videos
        mkdir -p $HOME/Music
      '';
    };
  };

  # Enable management of known folders
  xdg = {
    enable = true;
    userDirs = {
      enable = true;
      desktop = "${home.homeDirectory}/Desktop";
      documents = "${home.homeDirectory}/Documents";
      pictures = "${home.homeDirectory}/Pictures";
      videos = "${home.homeDirectory}/Videos";
      music = "${home.homeDirectory}/Music";
    };
    configFile = {
      "qt5ct/qt5ct.conf".source = ./res/qt5ct.conf;
      waybar.source = ./res/waybar;
      "hyfetch.json".source = ./res/hyfetch.json;
      "gtk-3.0/settings.ini".source = ./res/gtk/settings.ini;
      "gtk-4.0/settings.ini".source = ./res/gtk/settings.ini;
      "Kvantum/kvantum.kvconfig".text = ''
        [General]
        theme=Sweet-Ambar-Blue
      '';
      "gtklock/config.ini".text = ''
        [main]
        time-format=%I:%M %p\n%A %B %d
        gtk-theme=Sweet-Ambar-Blue
        background=${./res/pictures/background.jpg}
        idle-hide=true
        style=${./res/gtklock-style.css}
        start-hidden=true
        modules=/run/current-system/sw/lib/gtklock/userinfo-module.so
      '';
      "kdeconnect/config".text = ''
        [General]
        name=${hostName}
      '';
      "hypr/hyprpaper.conf".text = ''
        ipc = off
        preload = ${./res/pictures/background.jpg}
        wallpaper = eDP-1,${./res/pictures/background.jpg}
      '';
    };
    mimeApps = {
      enable = true;
      defaultApplications = {
        "text/html" = ["firefox.desktop" "chromium.desktop"];
        "x-scheme-handler/http" = ["firefox.desktop" "chromium.desktop"];
        "x-scheme-handler/https" = ["firefox.desktop" "chromium.desktop"];
        "x-scheme-handler/chrome" = ["firefox.desktop" "chromium.desktop"];
        "x-scheme-handler/vscode" = ["code-url-handler.desktop"];
        "application/x-extension-htm" = ["firefox.desktop" "chromium.desktop"];
        "application/x-extension-html" = ["firefox.desktop" "chromium.desktop"];
        "application/x-extension-shtml" = ["firefox.desktop" "chromium.desktop"];
        "application/x-extension-xht" = ["firefox.desktop" "chromium.desktop"];
        "application/x-extension-xhtml" = ["firefox.desktop" "chromium.desktop"];
        "application/xhtml+xml" = ["firefox.desktop" "chromium.desktop"];
        "application/pdf" = ["firefox.desktop" "chromium.desktop"];
        "inode/directory" = ["org.kde.dolphin.desktop"];
        "x-scheme-handler/mailto" = ["userapp-Thunderbird-WKLTC2.desktop"];
        "message/rfc822" = ["userapp-Thunderbird-WKLTC2.desktop"];
        "x-scheme-handler/mid" = ["userapp-Thunderbird-WKLTC2.desktop"];
        "text/plain" = ["org.kde.kate.desktop"];
        "x-scheme-handler/x-github-client" = ["github-desktop.desktop"];
        "x-scheme-handler/x-github-desktop-auth" = ["github-desktop.desktop"];
      };
    };
  };

  qt = {
    enable = true;
    platformTheme = "qtct";
  };

  # Hyprland
  wayland.windowManager.hyprland = {
    enable = true;
    settings = {
      autogenerated = 0;
      monitor = ",2256x1504@60,0x0,1";
      general = {
        border_size = 2;
        resize_on_border = true;
        "col.active_border" = "rgb(ff0000) rgb(ff9a00) rgb(d0de21) rgb(4fdc4a) rgb(3fdad8) rgb(2fc9e2) rgb(1c7fee) rgb(5f15f2) rgb(ba0cf8) rgb(fb07d9) 45deg";
      };
      decoration = {
        rounding = 10;
      };
      input = {
        numlock_by_default = true;
        touchpad = {
          natural_scroll = true;
        };
      };
      gestures = {
        workspace_swipe = true;
      };
      xwayland = {
        force_zero_scaling = true;
      };
      misc = {
        enable_swallow = true;
        swallow_regex = "^(kitty)$";
        disable_hyprland_logo = true;
      };
      env = [
        "GTK_THEME,Sweet-Ambar-Blue:dark"
        "QT_QPA_PLATFORMTHEME,qt5ct"
        "IMAGE_EDITOR,/run/current-system/sw/bin/drawing"
      ];
      exec-once = [
        "eval $(ssh-agent)"
        "hyprpaper"
        "hyprctl setcursor Sweet-cursors 24"
        "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP"
        "[workspace 2] keepassxc /home/bean/Documents/Database.kdbx"
        "waybar"
        "wl-paste -p --type text --watch cliphist store"
        "wl-paste --type image --watch cliphist store"
        "swaync"
        "swayosd-server"
        "nm-applet"
        "playerctld"
        "[workspace 1 silent] discord"
        "[workspace 2] firefox"
        "[workspace 3 silent] code ${home.homeDirectory}/nix-conf"
        "[workspace 3 silent] kitty"
      ];
      bind = [
        "SUPER,S,exec,rofi -show drun -font \"FiraMono Nerd Font Mono 12\" -icon-theme \"candy-icons\" -show-icons"
        "SUPER SHIFT,E,exec,rofi -modi emoji -show emoji"
        "SUPER,Delete,exec,rofi -modi 'p:rofi-power-menu' -show p --symbols-font \"FiraMono Nerd Font Mono\""
        ",XF86PowerOff,exec,rofi -modi 'p:rofi-power-menu' -show p --symbols-font \"FiraMono Nerd Font Mono\""
        "SUPER ALT,C,exec,rofi -modi calc -show calc"
        "SUPER,I,exec,rofi-pulse-select source"
        "SUPER,O,exec,rofi-pulse-select sink"
        "SUPER,B,exec,rofi-bluetooth"
        "SUPER,Q,exec,firefox"
        "SUPER,E,exec,dolphin"
        "SUPER,T,exec,kitty"
        "SUPER,N,exec,swaync-client -t -sw"
        "SUPER,L,exec,gtklock"
        "SUPER,C,killactive,"
        "SUPER,D,exec,code"
        "SUPER,M,exit,"
        "SUPER,V,exec,cliphist list | rofi -dmenu | cliphist decode | wl-copy,"
        "SUPER,P,pseudo,"
        "SUPER,J,togglesplit,"
        "SUPER,left,movefocus,l"
        "SUPER,right,movefocus,r"
        "SUPER,up,movefocus,u"
        "SUPER,down,movefocus,d"
        "SUPER,1,workspace,1"
        "SUPER,2,workspace,2"
        "SUPER,3,workspace,3"
        "SUPER,4,workspace,4"
        "SUPER,5,workspace,5"
        "SUPER,6,workspace,6"
        "SUPER,7,workspace,7"
        "SUPER,8,workspace,8"
        "SUPER,9,workspace,9"
        "SUPER,0,workspace,10"
        "SUPER SHIFT,1,movetoworkspace,1"
        "SUPER SHIFT,2,movetoworkspace,2"
        "SUPER SHIFT,3,movetoworkspace,3"
        "SUPER SHIFT,4,movetoworkspace,4"
        "SUPER SHIFT,5,movetoworkspace,5"
        "SUPER SHIFT,6,movetoworkspace,6"
        "SUPER SHIFT,7,movetoworkspace,7"
        "SUPER SHIFT,8,movetoworkspace,8"
        "SUPER SHIFT,9,movetoworkspace,9"
        "SUPER SHIFT,0,movetoworkspace,10"
        "SUPER SHIFT,S,exec,grimblast --freeze --notify copysave area"
        "SUPER SHIFT,R,exec,wl-screenrec -g \"$(slurp)\""
        "SUPER SHIFT,C,exec,hyprpicker"
        "SUPER SHIFT ALT,R,exec,wl-screenrec"
        ",XF86AudioRaiseVolume,exec,swayosd-client --output-volume raise"
        ",XF86AudioLowerVolume,exec,swayosd-client --output-volume lower"
        ",XF86AudioMute,exec,swayosd-client --output-volume mute-toggle"
        ",XF86MonBrightnessUp,exec,swayosd-client --brightness raise"
        ",XF86MonBrightnessDown,exec,swayosd-client --brightness lower"
      ];
      bindl = [
        ",switch:Lid Switch,exec,gtklock"
      ];
      bindr = [
        ",Caps_Lock,exec,swayosd-client --caps-lock"
      ];
      bindm = [
        "SUPER,mouse:272,movewindow"
        "SUPER,mouse:273,resizewindow"
      ];
    };
  };

  programs = {
    # Shell
    starship = {
      enable = true;
      settings = fromTOML (fileContents ./res/starship.toml);
    };

    nushell = {
      enable = true;
      configFile.text = ''
        $env.config = { show_banner: false }
      '';
      envFile.text = ''
        alias py = python
        alias cat = bat
        alias neofetch = hyfetch
      '';
    };

    rofi = {
      enable = true;
      package = pkgs.rofi-wayland;
      location = "center";
      theme = ./res/rofi-style.rasi;
      plugins = with pkgs; [
        rofi-emoji
        rofi-power-menu
        rofi-bluetooth
        rofi-calc
        rofi-pulse-select
      ];
    };

    # CLI Tools
    bat.enable = true;
    ripgrep.enable = true;
    gh = {
      enable = true;
      gitCredentialHelper.enable = true;
    };
    neovim = {
      enable = true;
      viAlias = true;
      vimAlias = true;
    };

    kitty = {
        enable = true;
        font = {
            name = "FiraMono Nerd Font Mono";
            size = 18;
        };
        theme = "Adwaita darker";
    };

    # GUI Apps
    chromium.enable = true;
    thunderbird = {
      enable = true;
      profiles.bean.isDefault = true;
    };
  };

  # Enable KDE Connect
  services = {
    ssh-agent.enable = true;
    kdeconnect.enable = true;
    gpg-agent = {
      enable = true;
      defaultCacheTtl = 1800;
      enableSshSupport = true;
    };
  };
}
