# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](grey)[ \
$os\
$hostname\
$username\
[](bg:grey #999999)\
$directory\
([](bg:grey #999999)\
$git_branch\
$git_commit\
$git_state)\
([](bg:grey #999999)\
$nodejs\
$python\
$rust)](bg:grey)\
[ ](grey)"""

right_format = """
[ ](grey)
($character$status[](bg:grey #999999))
($cmd_duration[](bg:grey #999999))\
$time\
[▓▒░](grey)
"""

palette = "main"
add_newline = false

[palettes.main]
grey = "#303030"
lightgrey = "#e5e5e5"
header = "blue"
footer = "green"

[line_break]
disabled = true

[hostname]
format = "[$hostname( $ssh_symbol) ]($style)"
ssh_only = false
ssh_symbol = ""
style = "bold header bg:grey"

[username]
format = "[$user ]($style)"
style_user = "header bg:grey"
style_root = "bold red bg:grey"
show_always = true

[os]
style = "bg:grey bold lightgrey"
disabled = false
format = "[$symbol ]($style)"

[os.symbols]
Raspbian = ""
Debian = ""
Macos = ""
Linux = ""
Windows = ""
Ubuntu = ""
Manjaro = ""
Android = ""

[directory]
truncation_length = 10
truncate_to_repo = true
home_symbol = ""
read_only = ""
style = "bold footer bg:grey"
format = "[ ($read_only )$path ]($style)"

[git_branch]
symbol = ""
style = "bg:grey footer"
format = '[ $symbol ($branch )]($style)'

[git_status]
conflicted = ""
modified = ""
style = "bg:grey footer"
format = '[$all_status $ahead_behind ]($style)'

[nodejs]
symbol = ""
style = "bg:grey footer"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:grey footer"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:grey footer"
format = '[ $symbol ($version) ]($style)'

[character]
disabled = false
success_symbol = "[](bold footer bg:grey)"
error_symbol = "[](bold red bg:grey)"
format = "[ $symbol ](bg:grey)"

[status]
disabled = false
style = "bg:grey red"
format = "[$status ]($style)"

[cmd_duration]
disabled = false
min_time = 2000
style = "bg:grey header"
format = "[ $duration  ]($style)"

[time]
disabled = false
use_12hr = true
time_format = "%a %b %e %I:%M %p "
style="bg:grey bold header"
format = "[ $time ]($style)"
