# Get editor completions crustd on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](crust)[ \
$os\
$hostname\
[](bg:crust #999999)\
$shell\
$username\
[](bg:crust #999999)\
$directory\
([](bg:crust #999999)\
$git_branch\
$git_commit\
$git_state)\
([](bg:crust #999999)\
$nodejs\
$python\
$rust\
$nix_shell)](bg:crust)\
[ ](crust)"""

right_format = """
[ ](crust)
($character$status[](bg:crust #999999))
($cmd_duration[](bg:crust #999999))\
$time\
[▓▒░](crust)
"""

# palette = "main"
add_newline = false

# [palettes.main]
# grey = "#303030"
# lightgrey = "#e5e5e5"
# blue = "blue"
# green = "green"

[line_break]
disabled = true

[hostname]
format = "[$hostname( $ssh_symbol) ]($style)"
ssh_only = false
ssh_symbol = ""
style = "bold blue bg:crust"

[username]
format = "[$user ]($style)"
style_user = "blue bg:crust"
style_root = "bold red bg:crust"
show_always = true

[os]
style = "bg:crust bold lightcrust"
disabled = false
format = "[$symbol ]($style)"

[os.symbols]
Raspbian = ""
Debian = ""
Macos = ""
Linux = ""
Windows = ""
Ubuntu = ""
Manjaro = ""
Android = ""
NixOS = "󱄅"

[directory]
truncation_length = 10
truncate_to_repo = true
home_symbol = "󰋜"
read_only = "󰌾"
style = "bold green bg:crust"
format = "[ ($read_only )$path ]($style)"

[git_branch]
symbol = "󰘬"
style = "bg:crust green"
format = '[ $symbol ($branch )]($style)'

[git_status]
conflicted = "󰀦"
modified = "󰏫"
style = "bg:crust green"
format = '[$all_status $ahead_behind ]($style)'

[git_state]
revert = "󰕍"
rebase = "󱗬"
merge = "󰘭"
style = "bg:crust green yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\)'

[nodejs]
symbol = "󰎙"
style = "bg:crust green"
not_capable_style = "bg:crust green bold red"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "󰌠"
style = "bg:crust green"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "󱘗"
style = "bg:crust green"
format = '[ $symbol ($version) ]($style)'

[nix_shell]
impure_msg = '[󱄅 impure](bold red bg:crust)'
pure_msg = '[󱄅](bold green bg:crust)'
unknown_msg = '[󱄅 unknown](bold yellow bg:crust)'
style = "bg:crust green"
format = '[ $state ](bold blue bg:crust) '

[character]
disabled = false
success_symbol = "[󰗠](bold green bg:crust)"
error_symbol = "[󰀨](bold red bg:crust)"
format = "[ $symbol ](bg:crust)"

[status]
disabled = false
style = "bg:crust red"
format = "[$status ]($style)"

[cmd_duration]
disabled = false
min_time = 2000
style = "bg:crust blue"
format = "[ 󱎫 $duration ]($style)"

[time]
disabled = false
use_12hr = true
time_format = "%a %b %d %I:%M %p 󰥔"
style = "bg:crust bold blue"
format = "[ $time ]($style)"

[shell]
fish_indicator = '󰈺'
powershell_indicator = '󰨊'
nu_indicator = '󰨊'
bash_indicator = "󱆃"
unknown_indicator = '󰋗'
style = 'bg:crust blue'
format = '[ $indicator ]($style)'
disabled = false